package com.gautam.Heavy_resource_pooling.model;

import java.util.UUID;

public class ExportEngine {
    private final String engineId;

    public ExportEngine() {
        this.engineId = UUID.randomUUID().toString().substring(0, 8);
        try {
            // Simulating expensive initialization (e.g., connecting to a legacy system, loading heavy fonts)
            Thread.sleep(2000);
            System.out.println("Initialized heavy ExportEngine: " + engineId);
        } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
        }
    }

    public String generateReport(String data) {
        // Simulating work
        return "Report [" + data + "] generated by Engine-" + engineId;
    }

    public String getEngineId() {
        return engineId;
    }
}
